#!/usr/bin/awk -f

/^warning:/ {
    # Store the warning line
    warning=$0
    # Keep reading lines until we hit a blank line
    while ((getline line) > 0 && line != "") {
        # Store each line of the warning
    }
    # Skip this entire warning block
    next
}
{ print }
